import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
  component: PrivacyPage,
  head: () => ({
    meta: [
      { title: "Privacy Policy — Tobi AI" },
      { name: "description", content: "How Tobi AI collects, uses, and protects your account data, conversations, and memory facts. Read the full privacy policy." },
      { property: "og:title", content: "Privacy Policy — Tobi AI" },
      { property: "og:description", content: "How Tobi AI handles your account, chats, and memory data." },
      { property: "og:url", content: "https://t-obi.xyz/privacy" },
    ],
    links: [{ rel: "canonical", href: "https://t-obi.xyz/privacy" }],
  }),
});

function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <div className="flex items-center gap-3 mb-8">
          <Link to="/" className="inline-flex rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground hover:opacity-90">
            ← Back to Tobi
          </Link>
        </div>
        <h1 className="font-display text-4xl font-bold mb-8">Privacy Policy</h1>
        <p className="text-muted-foreground mb-8">Last updated: May 25, 2026</p>

        <div className="space-y-8 text-sm leading-relaxed text-foreground/90">
          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">1. Information We Collect</h2>
            <p>When you use Tobi, we may collect:</p>
            <ul className="list-disc ml-5 mt-2 space-y-1">
              <li><strong>Account information:</strong> Email address, name, and authentication data when you sign up or log in</li>
              <li><strong>Conversational data:</strong> Messages and queries you send to Tobi, and responses generated by the AI</li>
              <li><strong>User facts:</strong> Information Tobi learns about you to personalize responses (with your consent)</li>
              <li><strong>Usage data:</strong> How you interact with the Service, including feature usage and error logs</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">2. How We Use Your Information</h2>
            <p>We use your information to:</p>
            <ul className="list-disc ml-5 mt-2 space-y-1">
              <li>Provide and improve the Service</li>
              <li>Personalize your experience with Tobi</li>
              <li>Maintain and secure your account</li>
              <li>Communicate with you about the Service</li>
              <li>Comply with legal obligations</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">3. AI Learning &amp; User Consent</h2>
            <p>Tobi may ask if it can learn from your conversation to improve future responses. This is entirely optional — you can accept or decline on a per-conversation basis. We implement rate limits on how often Tobi asks for consent to respect your privacy. You may also opt out entirely via your account settings.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">4. Data Retention</h2>
            <p>We retain your data for as long as your account is active or as needed to provide the Service. Conversational data may be stored to maintain conversation history and improve the Service. We limit the amount of personalized data ("user facts") stored per user to a maximum of 100 facts. When the limit is reached, older facts are automatically removed to make room for new ones.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">5. Data Sharing</h2>
            <p>We do not sell your personal data. We may share information with:</p>
            <ul className="list-disc ml-5 mt-2 space-y-1">
              <li><strong>Service providers:</strong> Third-party services that help us operate Tobi (e.g., cloud infrastructure, AI model providers)</li>
              <li><strong>Legal requirements:</strong> When required by law, court order, or to protect our rights</li>
              <li><strong>Business transfers:</strong> In connection with a merger, acquisition, or sale of assets</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">6. Your Rights</h2>
            <p>Depending on your location, you may have the right to:</p>
            <ul className="list-disc ml-5 mt-2 space-y-1">
              <li>Access the personal data we hold about you</li>
              <li>Correct inaccurate or incomplete data</li>
              <li>Delete your personal data</li>
              <li>Withdraw consent for AI learning</li>
              <li>Export your data</li>
            </ul>
            <p className="mt-2">To exercise these rights, contact us at <a href="mailto:tobyfemi@proton.me" className="underline text-tobi">tobyfemi@proton.me</a>.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">7. Security</h2>
            <p>We take reasonable measures to protect your data, including encryption in transit and at rest, access controls, and regular security reviews. However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">8. Cookies &amp; Tracking</h2>
            <p>We use minimal cookies and local storage necessary for authentication and session management. We do not use third-party tracking cookies or analytics that identify you personally.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">9. Children's Privacy</h2>
            <p>The Service is not intended for use by children under 13. We do not knowingly collect personal data from children under 13. If you believe we have collected data from a child under 13, please contact us immediately.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">10. Changes to This Policy</h2>
            <p>We may update this Privacy Policy from time to time. We will notify you of significant changes by posting the updated policy with a revised date. Your continued use of the Service after changes constitutes acceptance of the revised policy.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3 text-foreground">11. Contact Us</h2>
            <p>If you have questions or concerns about this Privacy Policy or your data, please contact us at <a href="mailto:tobyfemi@proton.me" className="underline text-tobi">tobyfemi@proton.me</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
